### ISSUE TITLE
Add severity colors to css

### ISSUE THREAD

**Issue by evanstoner** [CrowdStrike/alloy-react#42]
```css
html {
  /* default light mode */
  --critical: #e9181f;
  --high: #ff7e00;
  --medium: #edb000;
  --low: #649f64;
  --informational: #5082d2;
}

.pf-v6-theme-dark {
  --critical: #fa4147;
  --high: #f77d40;
  --medium: #ffcc00;
  --low: #cef2ce;
  --informational: #9dc1fd;
}
```
